import { PrismaClient } from '@prisma/client'

interface VocabEntry {
  word: string
  pronunciation: string
  partOfSpeech: string
  definition: string
  example: string
  synonyms: string
  collocations: string[]
  topic: string
  band: number
  cefr: string
  isAWL: boolean
  antonyms?: string
}

// ============================================================
// AWL SUBLIST 1 — Most frequent 60 academic words
// (Coxhead 2000, public domain word list)
// ============================================================
const AWL_SUBLIST_1: VocabEntry[] = [
  { word: 'analyse', pronunciation: '/ˈæn.əl.aɪz/', partOfSpeech: 'verb', definition: 'to study or examine something in detail to understand it', example: 'Scientists analyse data to find patterns in climate change.', synonyms: 'examine, investigate, study', collocations: ['analyse data', 'analyse results', 'analyse the situation'], topic: 'academic', band: 6, cefr: 'B2', isAWL: true },
  { word: 'approach', pronunciation: '/əˈprəʊtʃ/', partOfSpeech: 'noun/verb', definition: 'a way of dealing with something; to come near to something', example: 'A new approach to teaching languages has shown remarkable results.', synonyms: 'method, way, technique', collocations: ['adopt an approach', 'a different approach', 'approach a problem'], topic: 'academic', band: 6, cefr: 'B2', isAWL: true },
  { word: 'area', pronunciation: '/ˈeə.ri.ə/', partOfSpeech: 'noun', definition: 'a particular subject, activity, or region', example: 'The government should invest more in the area of renewable energy.', synonyms: 'field, region, sector', collocations: ['urban area', 'rural area', 'area of expertise'], topic: 'academic', band: 5, cefr: 'B1', isAWL: true },
  { word: 'assess', pronunciation: '/əˈses/', partOfSpeech: 'verb', definition: 'to make a judgment about the value or quality of something', example: 'Teachers assess students through tests and assignments.', synonyms: 'evaluate, judge, appraise', collocations: ['assess the impact', 'assess the situation', 'assess the risk'], topic: 'academic', band: 6, cefr: 'B2', isAWL: true },
  { word: 'assume', pronunciation: '/əˈsjuːm/', partOfSpeech: 'verb', definition: 'to accept that something is true without proof', example: 'Many people assume that wealth leads to happiness.', synonyms: 'presume, suppose, take for granted', collocations: ['assume responsibility', 'assume control', 'wrongly assume'], topic: 'academic', band: 6, cefr: 'B2', isAWL: true },
  { word: 'authority', pronunciation: '/ɔːˈθɒr.ə.ti/', partOfSpeech: 'noun', definition: 'the power to make decisions or give orders', example: 'Local authorities are responsible for managing public services.', synonyms: 'power, control, command', collocations: ['government authority', 'have authority over', 'figure of authority'], topic: 'society', band: 6, cefr: 'B2', isAWL: true },
  { word: 'benefit', pronunciation: '/ˈben.ɪ.fɪt/', partOfSpeech: 'noun/verb', definition: 'a helpful or good effect that something has', example: 'Regular exercise provides numerous health benefits.', synonyms: 'advantage, gain, profit', collocations: ['major benefit', 'reap the benefits', 'benefit from'], topic: 'health', band: 5, cefr: 'B1', isAWL: true, antonyms: 'drawback, disadvantage' },
  { word: 'concept', pronunciation: '/ˈkɒn.sept/', partOfSpeech: 'noun', definition: 'a principle or idea', example: 'The concept of sustainable development has gained popularity.', synonyms: 'idea, notion, principle', collocations: ['basic concept', 'abstract concept', 'grasp a concept'], topic: 'academic', band: 6, cefr: 'B2', isAWL: true },
  { word: 'consist', pronunciation: '/kənˈsɪst/', partOfSpeech: 'verb', definition: 'to be made up of particular things or people', example: 'The committee consists of ten members from different countries.', synonyms: 'comprise, contain, include', collocations: ['consist of', 'consist mainly of', 'consist entirely of'], topic: 'academic', band: 6, cefr: 'B2', isAWL: true },
  { word: 'context', pronunciation: '/ˈkɒn.tekst/', partOfSpeech: 'noun', definition: 'the situation in which something happens', example: 'Words can have different meanings depending on the context.', synonyms: 'situation, setting, background', collocations: ['social context', 'historical context', 'in this context'], topic: 'academic', band: 6, cefr: 'B2', isAWL: true },
  { word: 'create', pronunciation: '/kriˈeɪt/', partOfSpeech: 'verb', definition: 'to make something exist that did not exist before', example: 'The new policy will create thousands of jobs.', synonyms: 'produce, generate, establish', collocations: ['create opportunities', 'create awareness', 'create a problem'], topic: 'general', band: 5, cefr: 'B1', isAWL: true, antonyms: 'destroy' },
  { word: 'data', pronunciation: '/ˈdeɪ.tə/', partOfSpeech: 'noun', definition: 'facts or information used for analysis', example: 'The research data clearly shows a rise in temperature.', synonyms: 'information, facts, statistics', collocations: ['collect data', 'analyse data', 'data shows'], topic: 'technology', band: 5, cefr: 'B1', isAWL: true },
  { word: 'define', pronunciation: '/dɪˈfaɪn/', partOfSpeech: 'verb', definition: 'to say exactly what something means', example: 'It is difficult to define happiness precisely.', synonyms: 'describe, specify, explain', collocations: ['clearly define', 'define a term', 'define the role'], topic: 'academic', band: 6, cefr: 'B2', isAWL: true },
  { word: 'derive', pronunciation: '/dɪˈraɪv/', partOfSpeech: 'verb', definition: 'to get something from a particular source', example: 'Many English words derive from Latin.', synonyms: 'obtain, get, acquire', collocations: ['derive from', 'derive pleasure', 'derive benefit'], topic: 'academic', band: 7, cefr: 'C1', isAWL: true },
  { word: 'distribute', pronunciation: '/dɪˈstrɪb.juːt/', partOfSpeech: 'verb', definition: 'to give out to a large number of people', example: 'The charity distributes food to homeless people.', synonyms: 'allocate, hand out, spread', collocations: ['distribute evenly', 'distribute among', 'distribute resources'], topic: 'society', band: 6, cefr: 'B2', isAWL: true },
  { word: 'economic', pronunciation: '/ˌiː.kəˈnɒm.ɪk/', partOfSpeech: 'adjective', definition: 'relating to the economy or money', example: 'Economic growth has slowed in recent years.', synonyms: 'financial, fiscal, monetary', collocations: ['economic growth', 'economic crisis', 'economic policy'], topic: 'economy', band: 6, cefr: 'B2', isAWL: true },
  { word: 'environment', pronunciation: '/ɪnˈvaɪ.rən.mənt/', partOfSpeech: 'noun', definition: 'the natural world; surroundings', example: 'We must protect the environment for future generations.', synonyms: 'surroundings, ecosystem, habitat', collocations: ['protect the environment', 'natural environment', 'damage the environment'], topic: 'environment', band: 5, cefr: 'B1', isAWL: true },
  { word: 'establish', pronunciation: '/ɪˈstæb.lɪʃ/', partOfSpeech: 'verb', definition: 'to start a company, organization, or system', example: 'The university was established in 1875.', synonyms: 'found, set up, create', collocations: ['establish a company', 'establish a relationship', 'firmly establish'], topic: 'general', band: 6, cefr: 'B2', isAWL: true },
  { word: 'estimate', pronunciation: '/ˈes.tɪ.meɪt/', partOfSpeech: 'verb/noun', definition: 'to guess the value of something based on information', example: 'Scientists estimate that 8 million tonnes of plastic enter the ocean each year.', synonyms: 'calculate, approximate, predict', collocations: ['rough estimate', 'estimate the cost', 'overall estimate'], topic: 'academic', band: 6, cefr: 'B2', isAWL: true },
  { word: 'evident', pronunciation: '/ˈev.ɪ.dənt/', partOfSpeech: 'adjective', definition: 'easy to see or understand', example: 'It is evident that climate change is affecting global weather patterns.', synonyms: 'clear, obvious, apparent', collocations: ['clearly evident', 'become evident', 'evident from'], topic: 'academic', band: 7, cefr: 'C1', isAWL: true, antonyms: 'unclear, vague' },
  { word: 'factor', pronunciation: '/ˈfæk.tər/', partOfSpeech: 'noun', definition: 'one of the things that influences a situation', example: 'Diet is a major factor in maintaining good health.', synonyms: 'element, cause, influence', collocations: ['key factor', 'major factor', 'contributing factor'], topic: 'academic', band: 6, cefr: 'B2', isAWL: true },
  { word: 'function', pronunciation: '/ˈfʌŋk.ʃən/', partOfSpeech: 'noun/verb', definition: 'the purpose of something; to work', example: 'The primary function of schools is to educate children.', synonyms: 'purpose, role, operate', collocations: ['function as', 'function properly', 'primary function'], topic: 'academic', band: 6, cefr: 'B2', isAWL: true },
  { word: 'identify', pronunciation: '/aɪˈden.tɪ.faɪ/', partOfSpeech: 'verb', definition: 'to recognize or name someone or something', example: 'Police were able to identify the suspect from CCTV footage.', synonyms: 'recognize, name, distinguish', collocations: ['identify a problem', 'identify the cause', 'easily identify'], topic: 'general', band: 6, cefr: 'B2', isAWL: true },
  { word: 'income', pronunciation: '/ˈɪŋ.kʌm/', partOfSpeech: 'noun', definition: 'money received from work or investments', example: 'Higher education usually leads to higher income.', synonyms: 'earnings, salary, revenue', collocations: ['low income', 'household income', 'income inequality'], topic: 'economy', band: 6, cefr: 'B2', isAWL: true, antonyms: 'expenditure, outgoings' },
  { word: 'indicate', pronunciation: '/ˈɪn.dɪ.keɪt/', partOfSpeech: 'verb', definition: 'to show that something is likely to be true', example: 'Recent studies indicate a growing concern about online privacy.', synonyms: 'suggest, show, demonstrate', collocations: ['clearly indicate', 'indicate that', 'figures indicate'], topic: 'academic', band: 6, cefr: 'B2', isAWL: true },
  { word: 'individual', pronunciation: '/ˌɪn.dɪˈvɪdʒ.u.əl/', partOfSpeech: 'adjective/noun', definition: 'a single person; separate', example: 'Each individual has the right to express their opinion.', synonyms: 'single, separate, personal', collocations: ['individual rights', 'every individual', 'individual freedom'], topic: 'society', band: 6, cefr: 'B2', isAWL: true, antonyms: 'collective, group' },
  { word: 'involve', pronunciation: '/ɪnˈvɒlv/', partOfSpeech: 'verb', definition: 'to include something as a necessary part', example: 'Teaching involves much more than just delivering information.', synonyms: 'include, entail, require', collocations: ['involve in', 'directly involve', 'involve risk'], topic: 'general', band: 6, cefr: 'B2', isAWL: true },
  { word: 'issue', pronunciation: '/ˈɪʃ.uː/', partOfSpeech: 'noun', definition: 'an important topic or problem for discussion', example: 'Climate change is one of the most pressing issues of our time.', synonyms: 'problem, matter, topic', collocations: ['serious issue', 'raise an issue', 'address an issue'], topic: 'society', band: 5, cefr: 'B1', isAWL: true },
  { word: 'major', pronunciation: '/ˈmeɪ.dʒər/', partOfSpeech: 'adjective', definition: 'very important or large', example: 'Pollution is a major problem in many cities.', synonyms: 'significant, main, primary', collocations: ['major problem', 'major change', 'major impact'], topic: 'general', band: 5, cefr: 'B1', isAWL: true, antonyms: 'minor' },
  { word: 'method', pronunciation: '/ˈmeθ.əd/', partOfSpeech: 'noun', definition: 'a particular way of doing something', example: 'Active learning methods improve student engagement.', synonyms: 'approach, technique, way', collocations: ['effective method', 'traditional method', 'teaching method'], topic: 'academic', band: 5, cefr: 'B1', isAWL: true },
  { word: 'occur', pronunciation: '/əˈkɜːr/', partOfSpeech: 'verb', definition: 'to happen', example: 'Natural disasters occur more frequently due to climate change.', synonyms: 'happen, take place, arise', collocations: ['frequently occur', 'occur naturally', 'occur to someone'], topic: 'general', band: 6, cefr: 'B2', isAWL: true },
  { word: 'policy', pronunciation: '/ˈpɒl.ə.si/', partOfSpeech: 'noun', definition: 'a set of ideas or plans for action', example: 'The government has implemented a new education policy.', synonyms: 'strategy, plan, regulation', collocations: ['public policy', 'foreign policy', 'implement a policy'], topic: 'society', band: 6, cefr: 'B2', isAWL: true },
  { word: 'principle', pronunciation: '/ˈprɪn.sə.pəl/', partOfSpeech: 'noun', definition: 'a basic idea or rule', example: 'Democracy is based on the principle of equality.', synonyms: 'rule, doctrine, standard', collocations: ['basic principle', 'fundamental principle', 'in principle'], topic: 'academic', band: 6, cefr: 'B2', isAWL: true },
  { word: 'process', pronunciation: '/ˈprəʊ.ses/', partOfSpeech: 'noun/verb', definition: 'a series of actions to achieve something', example: 'The recruitment process can take several weeks.', synonyms: 'procedure, method, system', collocations: ['ongoing process', 'lengthy process', 'process information'], topic: 'general', band: 5, cefr: 'B1', isAWL: true },
  { word: 'require', pronunciation: '/rɪˈkwaɪər/', partOfSpeech: 'verb', definition: 'to need something', example: 'Most jobs require some level of computer literacy.', synonyms: 'need, demand, necessitate', collocations: ['require attention', 'require effort', 'be required to'], topic: 'general', band: 5, cefr: 'B1', isAWL: true },
  { word: 'research', pronunciation: '/rɪˈsɜːtʃ/', partOfSpeech: 'noun/verb', definition: 'a detailed study to find new information', example: 'Recent research suggests that meditation reduces stress.', synonyms: 'study, investigation, inquiry', collocations: ['conduct research', 'research shows', 'extensive research'], topic: 'academic', band: 5, cefr: 'B1', isAWL: true },
  { word: 'respond', pronunciation: '/rɪˈspɒnd/', partOfSpeech: 'verb', definition: 'to react or reply', example: 'It is important that governments respond quickly to natural disasters.', synonyms: 'reply, react, answer', collocations: ['respond quickly', 'respond to', 'fail to respond'], topic: 'general', band: 6, cefr: 'B2', isAWL: true },
  { word: 'role', pronunciation: '/rəʊl/', partOfSpeech: 'noun', definition: 'the position or function of someone', example: 'Parents play a crucial role in their children\'s education.', synonyms: 'function, part, position', collocations: ['play a role', 'important role', 'role model'], topic: 'general', band: 5, cefr: 'B1', isAWL: true },
  { word: 'significant', pronunciation: '/sɪɡˈnɪf.ɪ.kənt/', partOfSpeech: 'adjective', definition: 'important or noticeable', example: 'There has been a significant increase in online shopping.', synonyms: 'important, considerable, notable', collocations: ['significant increase', 'highly significant', 'statistically significant'], topic: 'academic', band: 6, cefr: 'B2', isAWL: true, antonyms: 'insignificant, trivial' },
  { word: 'similar', pronunciation: '/ˈsɪm.ɪ.lər/', partOfSpeech: 'adjective', definition: 'almost the same', example: 'The two cities are similar in size and population.', synonyms: 'alike, comparable, analogous', collocations: ['very similar', 'similar to', 'remarkably similar'], topic: 'general', band: 5, cefr: 'B1', isAWL: true, antonyms: 'different, dissimilar' },
  { word: 'source', pronunciation: '/sɔːs/', partOfSpeech: 'noun', definition: 'the origin of something', example: 'Solar power is a renewable source of energy.', synonyms: 'origin, supply, root', collocations: ['main source', 'reliable source', 'source of income'], topic: 'general', band: 5, cefr: 'B1', isAWL: true },
  { word: 'specific', pronunciation: '/spəˈsɪf.ɪk/', partOfSpeech: 'adjective', definition: 'particular and detailed', example: 'Each country has its own specific cultural traditions.', synonyms: 'particular, precise, definite', collocations: ['specific example', 'be specific about', 'specific area'], topic: 'general', band: 6, cefr: 'B2', isAWL: true, antonyms: 'general, vague' },
  { word: 'structure', pronunciation: '/ˈstrʌk.tʃər/', partOfSpeech: 'noun', definition: 'the way something is built or organized', example: 'The essay has a clear structure with introduction and conclusion.', synonyms: 'organization, framework, arrangement', collocations: ['social structure', 'basic structure', 'structure of'], topic: 'academic', band: 6, cefr: 'B2', isAWL: true },
  { word: 'theory', pronunciation: '/ˈθɪə.ri/', partOfSpeech: 'noun', definition: 'an idea that explains how or why something happens', example: 'Darwin\'s theory of evolution is widely accepted by scientists.', synonyms: 'hypothesis, concept, idea', collocations: ['scientific theory', 'in theory', 'theory of'], topic: 'academic', band: 6, cefr: 'B2', isAWL: true, antonyms: 'practice' },
  { word: 'vary', pronunciation: '/ˈveə.ri/', partOfSpeech: 'verb', definition: 'to be different in size, amount, or degree', example: 'Prices vary considerably from shop to shop.', synonyms: 'differ, change, fluctuate', collocations: ['vary widely', 'vary considerably', 'vary depending on'], topic: 'general', band: 6, cefr: 'B2', isAWL: true, antonyms: 'remain constant' },
]

// ============================================================
// AWL SUBLIST 2 — Next 60 most frequent
// ============================================================
const AWL_SUBLIST_2: VocabEntry[] = [
  { word: 'achieve', pronunciation: '/əˈtʃiːv/', partOfSpeech: 'verb', definition: 'to succeed in doing something', example: 'She worked hard to achieve her goal of becoming a doctor.', synonyms: 'attain, accomplish, reach', collocations: ['achieve a goal', 'achieve success', 'difficult to achieve'], topic: 'general', band: 6, cefr: 'B2', isAWL: true },
  { word: 'acquire', pronunciation: '/əˈkwaɪər/', partOfSpeech: 'verb', definition: 'to get or obtain something', example: 'Children acquire language skills very quickly.', synonyms: 'obtain, gain, get', collocations: ['acquire knowledge', 'acquire skills', 'newly acquired'], topic: 'education', band: 7, cefr: 'C1', isAWL: true },
  { word: 'administrate', pronunciation: '/ədˈmɪn.ɪ.streɪt/', partOfSpeech: 'verb', definition: 'to organize and control something', example: 'The hospital is administered by a board of directors.', synonyms: 'manage, run, oversee', collocations: ['administer a test', 'administer aid', 'administer justice'], topic: 'general', band: 7, cefr: 'C1', isAWL: true },
  { word: 'affect', pronunciation: '/əˈfekt/', partOfSpeech: 'verb', definition: 'to influence or change someone or something', example: 'Air pollution affects millions of people worldwide.', synonyms: 'influence, impact, change', collocations: ['affect deeply', 'greatly affect', 'adversely affect'], topic: 'general', band: 5, cefr: 'B1', isAWL: true },
  { word: 'appropriate', pronunciation: '/əˈprəʊ.pri.ət/', partOfSpeech: 'adjective', definition: 'suitable or right for a particular situation', example: 'Formal clothing is appropriate for job interviews.', synonyms: 'suitable, fitting, proper', collocations: ['most appropriate', 'culturally appropriate', 'appropriate for'], topic: 'general', band: 6, cefr: 'B2', isAWL: true, antonyms: 'inappropriate' },
  { word: 'aspect', pronunciation: '/ˈæs.pekt/', partOfSpeech: 'noun', definition: 'one part or feature of something', example: 'Time management is the most challenging aspect of studying abroad.', synonyms: 'feature, element, side', collocations: ['important aspect', 'every aspect', 'positive aspect'], topic: 'academic', band: 6, cefr: 'B2', isAWL: true },
  { word: 'assist', pronunciation: '/əˈsɪst/', partOfSpeech: 'verb', definition: 'to help someone', example: 'The new software is designed to assist teachers with grading.', synonyms: 'help, aid, support', collocations: ['assist with', 'greatly assist', 'assist in'], topic: 'general', band: 6, cefr: 'B2', isAWL: true },
  { word: 'category', pronunciation: '/ˈkæt.ə.ɡər.i/', partOfSpeech: 'noun', definition: 'a group of things that share similar features', example: 'Books are arranged into different categories in the library.', synonyms: 'group, class, type', collocations: ['fall into a category', 'broad category', 'main category'], topic: 'academic', band: 6, cefr: 'B2', isAWL: true },
  { word: 'consume', pronunciation: '/kənˈsjuːm/', partOfSpeech: 'verb', definition: 'to use, eat, or drink something', example: 'Modern lifestyles consume vast amounts of energy.', synonyms: 'use, eat, deplete', collocations: ['consume energy', 'consume resources', 'time-consuming'], topic: 'environment', band: 6, cefr: 'B2', isAWL: true },
  { word: 'design', pronunciation: '/dɪˈzaɪn/', partOfSpeech: 'noun/verb', definition: 'to plan and create something', example: 'The architect designed a sustainable office building.', synonyms: 'plan, create, devise', collocations: ['design a system', 'innovative design', 'well-designed'], topic: 'general', band: 5, cefr: 'B1', isAWL: true },
  { word: 'distinct', pronunciation: '/dɪˈstɪŋkt/', partOfSpeech: 'adjective', definition: 'clearly different or separate', example: 'There is a distinct difference between formal and informal English.', synonyms: 'different, separate, clear', collocations: ['distinct from', 'clearly distinct', 'distinct advantage'], topic: 'academic', band: 7, cefr: 'C1', isAWL: true },
  { word: 'element', pronunciation: '/ˈel.ɪ.mənt/', partOfSpeech: 'noun', definition: 'one part of something', example: 'Trust is an essential element of any relationship.', synonyms: 'component, part, factor', collocations: ['key element', 'essential element', 'element of surprise'], topic: 'general', band: 6, cefr: 'B2', isAWL: true },
  { word: 'evaluate', pronunciation: '/ɪˈvæl.ju.eɪt/', partOfSpeech: 'verb', definition: 'to judge the quality or value of something', example: 'Teachers evaluate students based on multiple criteria.', synonyms: 'assess, judge, appraise', collocations: ['evaluate the effectiveness', 'critically evaluate', 'evaluate options'], topic: 'academic', band: 6, cefr: 'B2', isAWL: true },
  { word: 'feature', pronunciation: '/ˈfiː.tʃər/', partOfSpeech: 'noun/verb', definition: 'an important or noticeable part of something', example: 'The latest phones include facial recognition as a key feature.', synonyms: 'characteristic, aspect, attribute', collocations: ['key feature', 'distinctive feature', 'main feature'], topic: 'technology', band: 5, cefr: 'B1', isAWL: true },
  { word: 'impact', pronunciation: '/ˈɪm.pækt/', partOfSpeech: 'noun/verb', definition: 'a powerful effect', example: 'Social media has had a huge impact on how we communicate.', synonyms: 'effect, influence, consequence', collocations: ['have an impact', 'major impact', 'environmental impact'], topic: 'society', band: 6, cefr: 'B2', isAWL: true },
  { word: 'implement', pronunciation: '/ˈɪm.plɪ.ment/', partOfSpeech: 'verb', definition: 'to put a plan into action', example: 'The school will implement new safety procedures next term.', synonyms: 'execute, carry out, enforce', collocations: ['implement a policy', 'fully implement', 'implement changes'], topic: 'general', band: 7, cefr: 'C1', isAWL: true },
  { word: 'imply', pronunciation: '/ɪmˈplaɪ/', partOfSpeech: 'verb', definition: 'to suggest something without saying it directly', example: 'His silence seemed to imply disagreement.', synonyms: 'suggest, indicate, hint', collocations: ['strongly imply', 'imply that', 'clearly imply'], topic: 'academic', band: 7, cefr: 'C1', isAWL: true },
  { word: 'invest', pronunciation: '/ɪnˈvest/', partOfSpeech: 'verb', definition: 'to put money or effort into something for benefit', example: 'Governments should invest more in education.', synonyms: 'put money in, allocate, spend', collocations: ['invest in', 'invest heavily', 'invest time'], topic: 'economy', band: 6, cefr: 'B2', isAWL: true },
  { word: 'maintain', pronunciation: '/meɪnˈteɪn/', partOfSpeech: 'verb', definition: 'to keep something in good condition; to continue', example: 'Regular exercise helps maintain good health.', synonyms: 'preserve, sustain, keep', collocations: ['maintain a balance', 'maintain standards', 'difficult to maintain'], topic: 'general', band: 6, cefr: 'B2', isAWL: true },
  { word: 'normal', pronunciation: '/ˈnɔː.məl/', partOfSpeech: 'adjective', definition: 'usual or expected', example: 'It is normal to feel nervous before a big exam.', synonyms: 'usual, ordinary, regular', collocations: ['perfectly normal', 'return to normal', 'normal range'], topic: 'general', band: 5, cefr: 'B1', isAWL: true, antonyms: 'abnormal, unusual' },
  { word: 'obtain', pronunciation: '/əbˈteɪn/', partOfSpeech: 'verb', definition: 'to get something', example: 'Students must obtain permission before missing class.', synonyms: 'get, acquire, secure', collocations: ['obtain information', 'obtain a degree', 'easily obtain'], topic: 'general', band: 6, cefr: 'B2', isAWL: true },
  { word: 'participate', pronunciation: '/pɑːˈtɪs.ɪ.peɪt/', partOfSpeech: 'verb', definition: 'to take part in something', example: 'All students are encouraged to participate in class discussions.', synonyms: 'take part, engage, join', collocations: ['actively participate', 'participate in', 'fully participate'], topic: 'general', band: 6, cefr: 'B2', isAWL: true },
  { word: 'perceive', pronunciation: '/pəˈsiːv/', partOfSpeech: 'verb', definition: 'to notice or understand something', example: 'How people perceive risk often depends on their experience.', synonyms: 'see, view, understand', collocations: ['widely perceived', 'perceive as', 'perceive a threat'], topic: 'academic', band: 7, cefr: 'C1', isAWL: true },
  { word: 'positive', pronunciation: '/ˈpɒz.ə.tɪv/', partOfSpeech: 'adjective', definition: 'good or hopeful; sure something is true', example: 'The new policy has had a positive effect on student performance.', synonyms: 'good, beneficial, favourable', collocations: ['positive effect', 'highly positive', 'positive outlook'], topic: 'general', band: 5, cefr: 'B1', isAWL: true, antonyms: 'negative' },
  { word: 'potential', pronunciation: '/pəˈten.ʃəl/', partOfSpeech: 'adjective/noun', definition: 'possible in the future', example: 'Renewable energy has enormous potential to replace fossil fuels.', synonyms: 'possible, prospective, possibility', collocations: ['huge potential', 'realize potential', 'potential benefit'], topic: 'general', band: 6, cefr: 'B2', isAWL: true },
  { word: 'previous', pronunciation: '/ˈpriː.vi.əs/', partOfSpeech: 'adjective', definition: 'happening before something else', example: 'My previous job was much more demanding than this one.', synonyms: 'former, earlier, prior', collocations: ['previous experience', 'previous year', 'in previous studies'], topic: 'general', band: 5, cefr: 'B1', isAWL: true, antonyms: 'following, subsequent' },
  { word: 'primary', pronunciation: '/ˈpraɪ.mə.ri/', partOfSpeech: 'adjective', definition: 'most important or first', example: 'The primary cause of obesity is a poor diet.', synonyms: 'main, chief, principal', collocations: ['primary concern', 'primary source', 'primary education'], topic: 'general', band: 6, cefr: 'B2', isAWL: true, antonyms: 'secondary' },
  { word: 'purchase', pronunciation: '/ˈpɜː.tʃəs/', partOfSpeech: 'verb/noun', definition: 'to buy something', example: 'Online shopping has changed how we purchase goods.', synonyms: 'buy, acquire', collocations: ['purchase online', 'online purchase', 'recent purchase'], topic: 'economy', band: 6, cefr: 'B2', isAWL: true, antonyms: 'sell' },
  { word: 'range', pronunciation: '/reɪndʒ/', partOfSpeech: 'noun/verb', definition: 'a variety of similar things', example: 'The library offers a wide range of books.', synonyms: 'variety, selection, scope', collocations: ['wide range', 'broad range', 'within range'], topic: 'general', band: 5, cefr: 'B1', isAWL: true },
  { word: 'region', pronunciation: '/ˈriː.dʒən/', partOfSpeech: 'noun', definition: 'a particular area or part of a country', example: 'Mountainous regions have a unique climate.', synonyms: 'area, district, zone', collocations: ['the region of', 'mountainous region', 'urban region'], topic: 'geography', band: 5, cefr: 'B1', isAWL: true },
  { word: 'reliance', pronunciation: '/rɪˈlaɪ.əns/', partOfSpeech: 'noun', definition: 'dependence on someone or something', example: 'Our reliance on smartphones has grown significantly.', synonyms: 'dependence, trust, faith', collocations: ['heavy reliance', 'reliance on', 'reduce reliance'], topic: 'technology', band: 7, cefr: 'C1', isAWL: true },
  { word: 'select', pronunciation: '/sɪˈlekt/', partOfSpeech: 'verb', definition: 'to choose carefully', example: 'Please select the best answer from the options below.', synonyms: 'choose, pick, opt for', collocations: ['carefully select', 'select from', 'randomly select'], topic: 'general', band: 5, cefr: 'B1', isAWL: true },
  { word: 'site', pronunciation: '/saɪt/', partOfSpeech: 'noun', definition: 'a place where something is located', example: 'The construction site is closed to the public.', synonyms: 'location, place, spot', collocations: ['construction site', 'website', 'on site'], topic: 'general', band: 5, cefr: 'B1', isAWL: true },
  { word: 'strategy', pronunciation: '/ˈstræt.ə.dʒi/', partOfSpeech: 'noun', definition: 'a plan for achieving something', example: 'The company developed a new marketing strategy.', synonyms: 'plan, approach, tactic', collocations: ['develop a strategy', 'long-term strategy', 'effective strategy'], topic: 'general', band: 6, cefr: 'B2', isAWL: true },
  { word: 'survey', pronunciation: '/ˈsɜː.veɪ/', partOfSpeech: 'noun/verb', definition: 'a study of opinions or behavior', example: 'A recent survey shows that 70% of teenagers use social media daily.', synonyms: 'poll, study, questionnaire', collocations: ['conduct a survey', 'survey shows', 'national survey'], topic: 'academic', band: 6, cefr: 'B2', isAWL: true },
  { word: 'task', pronunciation: '/tɑːsk/', partOfSpeech: 'noun', definition: 'a piece of work to be done', example: 'Memorizing vocabulary is a challenging task for many students.', synonyms: 'job, duty, assignment', collocations: ['difficult task', 'complete a task', 'daunting task'], topic: 'general', band: 5, cefr: 'B1', isAWL: true },
  { word: 'transfer', pronunciation: '/trænsˈfɜːr/', partOfSpeech: 'verb/noun', definition: 'to move from one place to another', example: 'Money can be transferred between accounts within seconds.', synonyms: 'move, shift, relocate', collocations: ['transfer money', 'transfer skills', 'transfer of'], topic: 'general', band: 6, cefr: 'B2', isAWL: true },
  { word: 'transport', pronunciation: '/ˈtræn.spɔːt/', partOfSpeech: 'noun/verb', definition: 'a way of moving people or things', example: 'Public transport reduces traffic and air pollution.', synonyms: 'transit, conveyance, carry', collocations: ['public transport', 'transport system', 'transport goods'], topic: 'transport', band: 5, cefr: 'B1', isAWL: true },
  { word: 'undertake', pronunciation: '/ˌʌn.dəˈteɪk/', partOfSpeech: 'verb', definition: 'to start doing a piece of work', example: 'The team undertook a thorough investigation of the issue.', synonyms: 'begin, take on, embark on', collocations: ['undertake a task', 'undertake research', 'fully undertake'], topic: 'academic', band: 7, cefr: 'C1', isAWL: true },
]

// ============================================================
// TOPIC VOCAB — 10 IELTS topics × 12 words = 120 high-band words
// ============================================================
const TOPIC_VOCAB: VocabEntry[] = [
  // EDUCATION (band 6-7)
  { word: 'curriculum', pronunciation: '/kəˈrɪk.jə.ləm/', partOfSpeech: 'noun', definition: 'the subjects studied at a school or college', example: 'The school curriculum includes both academic and vocational subjects.', synonyms: 'syllabus, courses, programme', collocations: ['national curriculum', 'school curriculum', 'curriculum design'], topic: 'education', band: 7, cefr: 'C1', isAWL: false },
  { word: 'literacy', pronunciation: '/ˈlɪt.ər.ə.si/', partOfSpeech: 'noun', definition: 'the ability to read and write', example: 'Adult literacy rates have improved significantly in developing countries.', synonyms: 'reading and writing skills', collocations: ['adult literacy', 'literacy rate', 'computer literacy'], topic: 'education', band: 7, cefr: 'C1', isAWL: false, antonyms: 'illiteracy' },
  { word: 'mandatory', pronunciation: '/ˈmæn.də.tər.i/', partOfSpeech: 'adjective', definition: 'required by law or rules', example: 'Education is mandatory for children aged 6 to 16.', synonyms: 'compulsory, obligatory, required', collocations: ['mandatory requirement', 'mandatory training', 'become mandatory'], topic: 'education', band: 7, cefr: 'C1', isAWL: false, antonyms: 'optional, voluntary' },
  { word: 'vocational', pronunciation: '/vəʊˈkeɪ.ʃən.əl/', partOfSpeech: 'adjective', definition: 'relating to a particular job', example: 'Vocational training prepares students for specific careers.', synonyms: 'occupational, professional, career-related', collocations: ['vocational training', 'vocational education', 'vocational school'], topic: 'education', band: 7, cefr: 'C1', isAWL: false },
  { word: 'scholarship', pronunciation: '/ˈskɒl.ə.ʃɪp/', partOfSpeech: 'noun', definition: 'money given to support a student\'s education', example: 'She received a full scholarship to study at Oxford.', synonyms: 'grant, bursary, fellowship', collocations: ['full scholarship', 'win a scholarship', 'apply for a scholarship'], topic: 'education', band: 6, cefr: 'B2', isAWL: false },
  { word: 'tuition', pronunciation: '/tjuːˈɪʃ.ən/', partOfSpeech: 'noun', definition: 'money paid for teaching, especially at university', example: 'University tuition fees have risen sharply in recent years.', synonyms: 'fees, education costs', collocations: ['tuition fees', 'private tuition', 'free tuition'], topic: 'education', band: 6, cefr: 'B2', isAWL: false },
  // ENVIRONMENT (band 6-7)
  { word: 'sustainable', pronunciation: '/səˈsteɪ.nə.bəl/', partOfSpeech: 'adjective', definition: 'able to continue without harming the environment', example: 'Sustainable agriculture protects soil and biodiversity.', synonyms: 'eco-friendly, renewable, viable', collocations: ['sustainable development', 'sustainable energy', 'environmentally sustainable'], topic: 'environment', band: 7, cefr: 'C1', isAWL: true },
  { word: 'deforestation', pronunciation: '/diːˌfɒr.ɪˈsteɪ.ʃən/', partOfSpeech: 'noun', definition: 'the cutting down of large areas of forest', example: 'Deforestation contributes significantly to global warming.', synonyms: 'forest clearance, logging', collocations: ['large-scale deforestation', 'cause deforestation', 'tackle deforestation'], topic: 'environment', band: 7, cefr: 'C1', isAWL: false, antonyms: 'reforestation' },
  { word: 'biodiversity', pronunciation: '/ˌbaɪ.əʊ.daɪˈvɜː.sɪ.ti/', partOfSpeech: 'noun', definition: 'the variety of plants and animals in a particular place', example: 'Tropical rainforests are home to incredible biodiversity.', synonyms: 'biological diversity, variety of species', collocations: ['rich biodiversity', 'loss of biodiversity', 'biodiversity conservation'], topic: 'environment', band: 8, cefr: 'C1', isAWL: false },
  { word: 'emission', pronunciation: '/ɪˈmɪʃ.ən/', partOfSpeech: 'noun', definition: 'a gas or other substance released into the air', example: 'Cars produce greenhouse gas emissions that contribute to climate change.', synonyms: 'discharge, release, output', collocations: ['carbon emissions', 'greenhouse gas emissions', 'reduce emissions'], topic: 'environment', band: 7, cefr: 'C1', isAWL: false },
  { word: 'renewable', pronunciation: '/rɪˈnjuː.ə.bəl/', partOfSpeech: 'adjective', definition: 'able to be replaced naturally', example: 'Solar and wind power are renewable sources of energy.', synonyms: 'sustainable, inexhaustible', collocations: ['renewable energy', 'renewable resources', 'fully renewable'], topic: 'environment', band: 6, cefr: 'B2', isAWL: false, antonyms: 'non-renewable, finite' },
  { word: 'pollution', pronunciation: '/pəˈluː.ʃən/', partOfSpeech: 'noun', definition: 'damage caused to air, water, or land', example: 'Air pollution in major cities has reached dangerous levels.', synonyms: 'contamination, pollution', collocations: ['air pollution', 'reduce pollution', 'cause pollution'], topic: 'environment', band: 5, cefr: 'B1', isAWL: false },
  // TECHNOLOGY (band 6-7)
  { word: 'algorithm', pronunciation: '/ˈæl.ɡə.rɪð.əm/', partOfSpeech: 'noun', definition: 'a set of rules followed in calculations', example: 'Search engines use complex algorithms to rank websites.', synonyms: 'procedure, formula, system', collocations: ['complex algorithm', 'machine-learning algorithm', 'develop an algorithm'], topic: 'technology', band: 8, cefr: 'C1', isAWL: false },
  { word: 'innovation', pronunciation: '/ˌɪn.əˈveɪ.ʃən/', partOfSpeech: 'noun', definition: 'a new idea, product, or method', example: 'Innovation in medicine has saved millions of lives.', synonyms: 'invention, breakthrough, advance', collocations: ['technological innovation', 'foster innovation', 'innovation in'], topic: 'technology', band: 7, cefr: 'C1', isAWL: true },
  { word: 'automation', pronunciation: '/ˌɔː.təˈmeɪ.ʃən/', partOfSpeech: 'noun', definition: 'the use of machines to do work', example: 'Automation has replaced many manufacturing jobs.', synonyms: 'mechanization, computerization', collocations: ['increasing automation', 'home automation', 'automation of'], topic: 'technology', band: 7, cefr: 'C1', isAWL: true },
  { word: 'cybersecurity', pronunciation: '/ˈsaɪ.bə.sɪˌkjʊə.rə.ti/', partOfSpeech: 'noun', definition: 'protection of computer systems from attack', example: 'Companies invest heavily in cybersecurity to protect customer data.', synonyms: 'IT security, digital security', collocations: ['cybersecurity threat', 'cybersecurity breach', 'cybersecurity expert'], topic: 'technology', band: 8, cefr: 'C2', isAWL: false },
  { word: 'digital', pronunciation: '/ˈdɪdʒ.ɪ.təl/', partOfSpeech: 'adjective', definition: 'using or relating to computers and the internet', example: 'Many traditional businesses are adapting to the digital age.', synonyms: 'electronic, computerized, online', collocations: ['digital age', 'digital revolution', 'digital media'], topic: 'technology', band: 5, cefr: 'B1', isAWL: false, antonyms: 'analogue, physical' },
  { word: 'artificial intelligence', pronunciation: '/ˌɑː.tɪ.fɪʃ.əl ɪnˈtel.ɪ.dʒəns/', partOfSpeech: 'noun phrase', definition: 'the ability of machines to perform tasks that need human intelligence', example: 'Artificial intelligence is transforming healthcare diagnostics.', synonyms: 'AI, machine intelligence', collocations: ['advance in AI', 'AI technology', 'AI-powered'], topic: 'technology', band: 7, cefr: 'C1', isAWL: false },
  // HEALTH (band 6-7)
  { word: 'obesity', pronunciation: '/əʊˈbiː.sə.ti/', partOfSpeech: 'noun', definition: 'the condition of being seriously overweight', example: 'Childhood obesity rates have tripled over the past 30 years.', synonyms: 'overweight, fatness', collocations: ['childhood obesity', 'obesity rates', 'tackle obesity'], topic: 'health', band: 7, cefr: 'C1', isAWL: false },
  { word: 'sedentary', pronunciation: '/ˈsed.ən.tər.i/', partOfSpeech: 'adjective', definition: 'involving a lot of sitting and little exercise', example: 'A sedentary lifestyle increases the risk of heart disease.', synonyms: 'inactive, sitting, desk-bound', collocations: ['sedentary lifestyle', 'sedentary job', 'sedentary behaviour'], topic: 'health', band: 8, cefr: 'C1', isAWL: false, antonyms: 'active' },
  { word: 'nutrition', pronunciation: '/njuːˈtrɪʃ.ən/', partOfSpeech: 'noun', definition: 'food that provides energy for the body', example: 'Good nutrition is essential for children\'s growth and development.', synonyms: 'diet, nourishment', collocations: ['good nutrition', 'poor nutrition', 'nutrition education'], topic: 'health', band: 6, cefr: 'B2', isAWL: false },
  { word: 'epidemic', pronunciation: '/ˌep.ɪˈdem.ɪk/', partOfSpeech: 'noun', definition: 'the rapid spread of a disease', example: 'The flu epidemic affected millions of people.', synonyms: 'outbreak, plague, pandemic', collocations: ['flu epidemic', 'declare an epidemic', 'global epidemic'], topic: 'health', band: 7, cefr: 'C1', isAWL: false },
  { word: 'preventive', pronunciation: '/prɪˈven.tɪv/', partOfSpeech: 'adjective', definition: 'designed to prevent something from happening', example: 'Preventive healthcare can save lives and reduce costs.', synonyms: 'preventative, protective', collocations: ['preventive measures', 'preventive medicine', 'preventive care'], topic: 'health', band: 7, cefr: 'C1', isAWL: false, antonyms: 'curative' },
  { word: 'wellbeing', pronunciation: '/ˌwelˈbiː.ɪŋ/', partOfSpeech: 'noun', definition: 'the state of being healthy and happy', example: 'Mental wellbeing is just as important as physical health.', synonyms: 'welfare, health, happiness', collocations: ['mental wellbeing', 'sense of wellbeing', 'promote wellbeing'], topic: 'health', band: 6, cefr: 'B2', isAWL: false },
  // SOCIETY (band 6-7)
  { word: 'inequality', pronunciation: '/ˌɪn.ɪˈkwɒl.ə.ti/', partOfSpeech: 'noun', definition: 'an unfair difference between groups', example: 'Income inequality has widened in many developed countries.', synonyms: 'disparity, unfairness, imbalance', collocations: ['income inequality', 'social inequality', 'address inequality'], topic: 'society', band: 7, cefr: 'C1', isAWL: false, antonyms: 'equality' },
  { word: 'demographic', pronunciation: '/ˌdem.əˈɡræf.ɪk/', partOfSpeech: 'adjective/noun', definition: 'relating to the population structure', example: 'Demographic changes are reshaping the workforce.', synonyms: 'population-related', collocations: ['demographic change', 'demographic group', 'demographic trends'], topic: 'society', band: 7, cefr: 'C1', isAWL: false },
  { word: 'urbanization', pronunciation: '/ˌɜː.bən.aɪˈzeɪ.ʃən/', partOfSpeech: 'noun', definition: 'the movement of people to cities', example: 'Rapid urbanization has put pressure on housing and transport.', synonyms: 'urban growth, city expansion', collocations: ['rapid urbanization', 'mass urbanization', 'urbanization process'], topic: 'society', band: 8, cefr: 'C1', isAWL: false },
  { word: 'diverse', pronunciation: '/daɪˈvɜːs/', partOfSpeech: 'adjective', definition: 'including many different types', example: 'London is one of the most culturally diverse cities in the world.', synonyms: 'varied, different, multifaceted', collocations: ['culturally diverse', 'diverse range', 'diverse population'], topic: 'society', band: 6, cefr: 'B2', isAWL: true, antonyms: 'uniform, homogeneous' },
  { word: 'integration', pronunciation: '/ˌɪn.tɪˈɡreɪ.ʃən/', partOfSpeech: 'noun', definition: 'the process of mixing groups together', example: 'Successful integration depends on mutual understanding.', synonyms: 'inclusion, incorporation, assimilation', collocations: ['social integration', 'integration of', 'cultural integration'], topic: 'society', band: 7, cefr: 'C1', isAWL: true, antonyms: 'segregation' },
  { word: 'minority', pronunciation: '/maɪˈnɒr.ə.ti/', partOfSpeech: 'noun', definition: 'a smaller group within a larger one', example: 'Ethnic minorities are often underrepresented in government.', synonyms: 'small group, less common', collocations: ['ethnic minority', 'minority group', 'religious minority'], topic: 'society', band: 6, cefr: 'B2', isAWL: false, antonyms: 'majority' },
  // ECONOMY (band 6-7)
  { word: 'inflation', pronunciation: '/ɪnˈfleɪ.ʃən/', partOfSpeech: 'noun', definition: 'a general rise in prices', example: 'High inflation reduces the purchasing power of consumers.', synonyms: 'price rise, cost increase', collocations: ['high inflation', 'control inflation', 'inflation rate'], topic: 'economy', band: 7, cefr: 'C1', isAWL: false, antonyms: 'deflation' },
  { word: 'recession', pronunciation: '/rɪˈseʃ.ən/', partOfSpeech: 'noun', definition: 'a period of economic decline', example: 'The country entered a recession after the financial crisis.', synonyms: 'downturn, slump, depression', collocations: ['enter a recession', 'severe recession', 'economic recession'], topic: 'economy', band: 7, cefr: 'C1', isAWL: false, antonyms: 'boom, growth' },
  { word: 'unemployment', pronunciation: '/ˌʌn.ɪmˈplɔɪ.mənt/', partOfSpeech: 'noun', definition: 'the state of not having a job', example: 'Youth unemployment is a major concern in many countries.', synonyms: 'joblessness', collocations: ['youth unemployment', 'high unemployment', 'unemployment rate'], topic: 'economy', band: 6, cefr: 'B2', isAWL: false, antonyms: 'employment' },
  { word: 'globalization', pronunciation: '/ˌɡləʊ.bəl.aɪˈzeɪ.ʃən/', partOfSpeech: 'noun', definition: 'the process by which the world is becoming more connected', example: 'Globalization has both positive and negative effects on local economies.', synonyms: 'international integration', collocations: ['effects of globalization', 'rapid globalization', 'economic globalization'], topic: 'economy', band: 7, cefr: 'C1', isAWL: false },
  { word: 'monetary', pronunciation: '/ˈmʌn.ɪ.tər.i/', partOfSpeech: 'adjective', definition: 'relating to money', example: 'The central bank adjusts monetary policy to control inflation.', synonyms: 'financial, fiscal', collocations: ['monetary policy', 'monetary value', 'monetary system'], topic: 'economy', band: 8, cefr: 'C1', isAWL: true },
]

export async function seedVocab(db: PrismaClient, studentId: string) {
  const allWords = [...AWL_SUBLIST_1, ...AWL_SUBLIST_2, ...TOPIC_VOCAB]
  let count = 0
  // Spread due dates: half due now, rest staggered over next 14 days for natural FSRS rollout
  const now = new Date()
  for (let i = 0; i < allWords.length; i++) {
    const w = allWords[i]
    const dueOffset = i < allWords.length / 2 ? 0 : Math.floor(Math.random() * 14)
    const due = new Date(now.getTime() + dueOffset * 86_400_000)

    await db.vocabCard.upsert({
      where: { studentId_word: { studentId, word: w.word } },
      update: {
        definition: w.definition,
        example: w.example,
        pronunciation: w.pronunciation,
        topic: w.topic,
        band: w.band,
        cefr: w.cefr,
        isAWL: w.isAWL,
        partOfSpeech: w.partOfSpeech,
        synonyms: w.synonyms,
        antonyms: w.antonyms,
        collocations: JSON.stringify(w.collocations),
      },
      create: {
        studentId,
        word: w.word,
        definition: w.definition,
        example: w.example,
        pronunciation: w.pronunciation,
        topic: w.topic,
        band: w.band,
        cefr: w.cefr,
        isAWL: w.isAWL,
        partOfSpeech: w.partOfSpeech,
        synonyms: w.synonyms,
        antonyms: w.antonyms,
        collocations: JSON.stringify(w.collocations),
        dueDate: due,
        state: 'new',
      },
    })
    count++
  }
  console.log(`  ✓ ${count} vocab cards seeded (AWL Sublist 1-2 + 6 topic banks)`)
  return count
}
